spring:
  application:
    name: hello-spring-cloud-zuul

server:
  port: 8769

#   通过 registerWithEureka: false fetchRegistry: false 表示自己是服务端
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign