spring:
  application:
    name: hello-spring-cloud-eureka

server:
  port: 8761


#   通过 registerWithEureka: false fetchRegistry: false 表示自己是服务端
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/