spring:
  application:
    name: hello-spring-cloud-web-admin-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
server:
  port: 8764


#   通过 registerWithEureka: false fetchRegistry: false 表示自己是服务端
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/